---
title: "bls8 FAIR table"
format: 
  pdf:
    fontsize: 8pt
    mainfont: Helvetica
editor: visual
bibliography: references.bib
---

| FAIR principle   | Definition                                                                                                                                           | Application to biologging                                                                                                                                                                                                                                                | Example                                                                                                                                                                                                        |
|------------------|------------------|--------------------|------------------|
| Findability      | Data and metadata have a globally unique and persistent identifier (e.g., a digital object identifier, DOI) and are indexed in a searchable resource | Data repositories, like the Movebank Data Repository, improve data discoverability and may assign DOIs to data (avoiding issues with broken hyperlinks, for example)                                                                                                     | A tracking dataset deposited in the Movebank Data Repository is findable by its permanent DOI or by searching the repository.                                                                                  |
| Accessibility    | Data and metadata are retrievable by open and universal protocols, such as HTTP                                                                      | Data repositories allow scientists to retrieve biologging data via a web browser or other open source tools                                                                                                                                                              | Publicly available data on Movebank may be downloaded via the website, API, or with the `move2` R package [@kranstauber2023]                                                                                   |
| Interoperability | Data use formal and shared formats and vocabularies                                                                                                  | Shared protocols like the Darwin Core standard [@wieczorek2012], Movebank data model [@MPIAB2023], and proposed bio-logging standardization framework [@sequeira2021] reduce barriers to combining datasets and increase uptake within and across scientific disciplines | Location and environmental data from seal-borne biologgers harmonized to a standard netCDF format facilitated their reuse by oceanographers to study polar regions [@treasure2017]                             |
| Reusability      | Data and metadata are richly described and reuse permissions are clearly defined                                                                     | Data repositories and standards together capture essential context for biologging data and provide licensing options for data reuse                                                                                                                                      | The Movebank Data Repository releases datasets under the CC0 license and the Movebank data model [@MPIAB2023] includes fields important for data reuse, e.g., whether the animal was relocated before release. |
